version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_postgres
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 1221"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    restart: on-failure
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      db:
        condition: service_healthy

volumes:
    pg-data:



